--- 
title: "NHIS Anxiety Analysis in Adults"
author: "Zhe Wang, Yingyi Zhu, Zixiao Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

In today's rapidly developing and competitive society, almost everyone has a certain degree of anxiety, which is manifested in a variety of mild or severe psychological diseases and behavioral symptoms. When it comes to school, we are afraid that we can not complete the study task well and get a bad result. When it comes to the job, we may doubt our abilities and fear not finding a job. When it comes to inquires from family and friends, we are also afraid of disappointing those who care about us. When it comes to interpersonal relationships, we often fear contact with strangers and worry that our language or behavior will suffer from the negative evaluation of others. These can be seen as signs of anxiety. We started studying this topic because we are also facing more or less stress nowadays. We often feel the negative emotions caused by anxiety. So what we want to see from the data is how anxiety affects our life and health or how it relates to each other. 